version: '3.8'
services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/data
      - $HOME/.aws:/root/.aws
      - $HOME/.terraform.d/plugin-cache:/.plugin-cache
    environment:
      - TF_PLUGIN_CACHE_DIR=/.plugin-cache
